# SITE CONFIGURATION
title: Av.Ezgi Beri
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ezgiberi.av.tr/" # the base hostname & protocol for your site, e.g. http://example.com

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Hakkında', link: '/hakkinda/'}
  - {name: 'Hizmetler', link: '/hizmetler/'}
  - {name: 'Blog', link: '#'}
  - {name: 'İletişim', link: '/iletisim/'}

tagline: >
  Sorununuzu gelip bize danışın. Böylelikle avukatın kralıyla tanışın. - Av. Ezgi BERİ

hero_img: mersin-manzara.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: form@ezgiberi.av.tr # email for form submission

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
